before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: LGVcKeZStVB0EWJ20WoMW+LN/XJYqelQ50y8OdmA4d6DqfMuslb5B3rO/4O1+xhBCAWs4T5vMaNhUFr93P+dlf6hjxKQbkbfe4AdgPor8ld6+L8DMLeBTJ7PkREQCg7t6JRM4CCc0bWvzNuAG5mcjIVBPJdUkWiXIXAcRKqaW6wzk+5sueVpCItJC0d0zjLizy3kbbPe15WsZhzgvySvRro8iZeu9nIWOalhB25qYCE6EjM9SAdfFUTP6evsAgVmLmlTCbH1NK2R2SiE42biLHMYrA5K0k4RGFdFrcU8np5Zj7SCxR/H4DaOPozLyE4o7z84iuifeHWvN/VKSNOBEMiBM50KY9mIgKY6TRTVBC6t1fyfhyehnfCHYU8shI4PKgpjl5nLfe9+QpU0JgSvqDXkc6jr+UiKXB81aWxyKr6Jojr5DaFT3+e2HcLBEaDIDKrdnjBQvlm9ta0tZrTPAo+oag5G6gEvIOdLMqRllyf8vspXiLvOtHmGJXQiMmQuoj9xm5RJCFZiBDuytj8iFNqifDMwHQ8o9Ew2MG/exdNgXQKByPhxTk8dJvs+Q1rG9MxSG/LF+EyWtt15DR07YeIRmLA0JuhzZ9Y6Ri1NcuDpHrvvjEFgY/7FsAwUHTnB6RocFgxCd9LoSIzu7fc6o+07Uu9NxDNvJIxDSFozO3w= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
